services:
  tyk:
    image: tykio/tyk-gateway:v5.5.0
    ports:
      - 8080:8080
    volumes:
      - ./conf/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=changeme
    depends_on:
      - redis
  redis:
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379
  pump:
    image: tykio/tyk-pump-docker-pub:v1.11
    ports:
    - 8083:8083
    - 8084:8084
    volumes:
      - ./conf/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_LOGLEVEL=${PUMP_LOGLEVEL:-info}
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    volumes:
      - ./conf:/conf
      - ./prometheus_data:/data
    command:
      - '--config.file=/conf/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana_data/:/var/lib/grafana

